"""changed column name and data type in billboards table

Revision ID: 37fa869dc87c
Revises: a270d4e485ac
Create Date: 2019-01-03 11:27:52.983775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37fa869dc87c'
down_revision = 'a270d4e485ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billboards', sa.Column('bid_times', sa.ARRAY(sa.Numeric()), nullable=True))
    op.drop_column('billboards', 'successful_bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billboards', sa.Column('successful_bookings', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('billboards', 'bid_times')
    # ### end Alembic commands ###
