"""added is_approved and concepts columns to media table

Revision ID: 803f83d860e5
Revises: e000d899eaef
Create Date: 2019-01-01 02:20:16.930927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803f83d860e5'
down_revision = 'e000d899eaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('concepts', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('is_approved', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'is_approved')
    op.drop_column('media', 'concepts')
    # ### end Alembic commands ###
