"""added base price column for billboards

Revision ID: a270d4e485ac
Revises: d42c55c01ca7
Create Date: 2019-01-02 18:33:33.694250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a270d4e485ac'
down_revision = 'd42c55c01ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('base_price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text()),
    sa.Column('successful_bookings', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'bids', 'billboards', ['billboard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.drop_table('billboards')
    # ### end Alembic commands ###
