"""added campaign name and description to m media table

Revision ID: e000d899eaef
Revises: 2bc2f4d7d481
Create Date: 2018-12-27 15:02:46.654710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e000d899eaef'
down_revision = '2bc2f4d7d481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('campaign_name', sa.Text(), server_default='', nullable=False))
    op.add_column('media', sa.Column('description', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'description')
    op.drop_column('media', 'campaign_name')
    # ### end Alembic commands ###
