"""added bids and billboard models

Revision ID: e8b63a273dbf
Revises: 803f83d860e5
Create Date: 2019-01-02 04:28:11.459710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b63a273dbf'
down_revision = '803f83d860e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('successful_bookings', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billboard_id', sa.Integer(), nullable=False),
    sa.Column('medium_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('booking_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['billboard_id'], ['billboards.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('successful_bookings', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'successful_bookings')
    op.drop_table('bids')
    op.drop_table('billboards')
    # ### end Alembic commands ###
